on: [push]

jobs:
  generate_cv_pdf:
    runs-on: ubuntu-latest
    name: A job to generate pdf version of my cv
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Make changes in repo
        run: echo hi > world.txt
      - name: commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: add world.txt
