on: [push]

jobs:
  generate_cv_pdf:
    runs-on: ubuntu-latest
    name: A job to generate pdf version of my cv
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: echo hi > world.txt
      - uses: actions/upload-artifact@v3
        with:
          path: world.txt
